apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: accionables-madlab

resources:
- namespace.yaml
- server-deployment.yaml
- server-service.yaml
- client-deployment.yaml
- client-service.yaml
- network-policies.yaml

images:
- digest: sha256:ea93059fc3cbec5868ed50d03322e5962094822990a184ffd060397c48b133d8
  name: ghcr.io/madfam-org/accionables-madlab-client
  newName: ghcr.io/madfam-org/accionables-madlab-client
- digest: sha256:4943cf32533ef2fb620b549b4024b8f5902863c2a4dec9953f87bb68ee0b18fd
  name: ghcr.io/madfam-org/accionables-madlab-server
  newName: ghcr.io/madfam-org/accionables-madlab-server
