apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: madlab

resources:
- namespace.yaml
- server-deployment.yaml
- server-service.yaml
- client-deployment.yaml
- client-service.yaml
- network-policies.yaml

images:
- digest: sha256:6a8891d68fe599ee3532817ac7edb2a99358bfb57bfa2ccb2996ab845cdc2ec4
  name: ghcr.io/madfam-org/accionables-madlab-client
  newName: ghcr.io/madfam-org/accionables-madlab-client
- digest: sha256:435049b68a1824330a10eef997baed3806c4d0de1a09aa574a0f58d32bf942d9
  name: ghcr.io/madfam-org/accionables-madlab-server
  newName: ghcr.io/madfam-org/accionables-madlab-server
