apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: madlab

resources:
  - namespace.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - server-deployment.yaml
  - server-service.yaml
  - client-deployment.yaml
  - client-service.yaml
  - network-policies.yaml

images:
  - name: ghcr.io/madfam-org/accionables-madlab-client
    newName: ghcr.io/madfam-org/accionables-madlab-client
    newTag: latest
  - name: ghcr.io/madfam-org/accionables-madlab-server
    newName: ghcr.io/madfam-org/accionables-madlab-server
    newTag: latest
