apiVersion: v1
kind: Service
metadata:
  name: madlab-server
  namespace: accionables-madlab
spec:
  selector:
    app: madlab-server
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
  type: ClusterIP
